version: "3"

services:
  spark-master:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    environment:
      - PYSPARK_PYTHON=python3.12
      - PYSPARK_DRIVER_PYTHON=python3.12
    hostname: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "0.0.0.0"]
    ports:
      - "7077:7077"  # Spark master port
      - "8080:8080"  # Spark UI
    volumes:
      - ~/shared-data:/shared-data  # Shared volume


  spark-worker-1:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-1
    environment:
      - PYSPARK_PYTHON=python3.12
      - PYSPARK_DRIVER_PYTHON=python3.12
    
    depends_on:
      - spark-master
    volumes:
      - ~/shared-data:/shared-data  # Shared volume

    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]

  spark-worker-2:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-2
    environment:
      - PYSPARK_PYTHON=python3.12
      - PYSPARK_DRIVER_PYTHON=python3.12
    depends_on:
      - spark-master
    volumes:
      - ~/shared-data:/shared-data  # Shared volume

    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
  airflow:
    image: airflow:latest
    volumes:
      - ./airflow:/opt/airflow
      - ~/shared-data:/shared-data  # Shared volume
      

    ports:
      - "8090:8080"
    
    command: airflow standalone
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      retries: 5
    restart: always

volumes:
  postgres_data:


 
